<?php

namespace Database\Seeders;

use App\Models\Club;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ClubSeeder extends Seeder
{
    public function run(): void
    {
        $clubs = [
            [
                'name'             => 'Barracuda Dive Club',
                'city'             => 'Denpasar',
                'area'             => 'denpasar',
                'icon'             => '🐟',
                'established_year' => 2003,
                'member_count'     => 87,
                'specialty'        => 'Freediving & Kompetisi',
                'description'      => 'Club selam tertua dan terprestasi di Denpasar, fokus pada pembinaan atlet freediving kompetitif tingkat nasional dan internasional.',
                'contact_phone'    => '+62 361 111 0001',
                'contact_email'    => 'barracuda@possibali.org',
                'is_verified'      => true,
                'is_champion'      => true,
                'is_active'        => true,
            ],
            [
                'name'             => 'Blue Coral Divers',
                'city'             => 'Badung',
                'area'             => 'badung',
                'icon'             => '🪸',
                'established_year' => 2008,
                'member_count'     => 64,
                'specialty'        => 'Reef Conservation',
                'description'      => 'Club selam yang berkomitmen pada konservasi terumbu karang di perairan Badung, aktif dalam program transplantasi dan monitoring karang.',
                'contact_phone'    => '+62 361 222 0002',
                'contact_email'    => 'bluecoral@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Manta Ray Club',
                'city'             => 'Karangasem',
                'area'             => 'karangasem',
                'icon'             => '🦈',
                'established_year' => 2011,
                'member_count'     => 52,
                'specialty'        => 'Deep Diving & Photography',
                'description'      => 'Spesialis deep diving dan underwater photography di perairan Karangasem, termasuk lokasi ikonik Tulamben dan Amed.',
                'contact_phone'    => '+62 363 333 0003',
                'contact_email'    => 'mantaray@possibali.org',
                'is_verified'      => true,
                'is_champion'      => true,
                'is_active'        => true,
            ],
            [
                'name'             => 'Tulamben Divers',
                'city'             => 'Karangasem',
                'area'             => 'karangasem',
                'icon'             => '⚓',
                'established_year' => 2006,
                'member_count'     => 78,
                'specialty'        => 'Wreck Diving',
                'description'      => 'Club spesialis wreck diving dengan keahlian utama menyelami bangkai kapal USAT Liberty, salah satu wreck dive terbaik dunia.',
                'contact_phone'    => '+62 363 444 0004',
                'contact_email'    => 'tulamben@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Pemuteran Sea Club',
                'city'             => 'Buleleng',
                'area'             => 'buleleng',
                'icon'             => '🐬',
                'established_year' => 2014,
                'member_count'     => 41,
                'specialty'        => 'Marine Education',
                'description'      => 'Club selam berbasis edukasi kelautan di Pemuteran, aktif menjalankan program biorock dan edukasi lingkungan laut untuk masyarakat setempat.',
                'contact_phone'    => '+62 362 555 0005',
                'contact_email'    => 'pemuteran@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Lovina Ocean Club',
                'city'             => 'Buleleng',
                'area'             => 'buleleng',
                'icon'             => '🌊',
                'established_year' => 2010,
                'member_count'     => 55,
                'specialty'        => 'Snorkeling & Freediving',
                'description'      => 'Club selam di kawasan wisata Lovina, mengembangkan snorkeling dan freediving sebagai olahraga rekreasi dan kompetitif di perairan utara Bali.',
                'contact_phone'    => '+62 362 666 0006',
                'contact_email'    => 'lovina@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Nusa Penida Divers',
                'city'             => 'Klungkung',
                'area'             => 'klungkung',
                'icon'             => '🐙',
                'established_year' => 2015,
                'member_count'     => 49,
                'specialty'        => 'Pelagic Diving',
                'description'      => 'Club selam yang mengkhususkan diri pada pelagic diving di perairan Nusa Penida, terkenal dengan dive spot Manta Point dan Crystal Bay.',
                'contact_phone'    => '+62 366 777 0007',
                'contact_email'    => 'nusapenida@possibali.org',
                'is_verified'      => true,
                'is_champion'      => true,
                'is_active'        => true,
            ],
            [
                'name'             => 'Kuta Sea Warriors',
                'city'             => 'Badung',
                'area'             => 'badung',
                'icon'             => '🏄',
                'established_year' => 2009,
                'member_count'     => 93,
                'specialty'        => 'Rescue Diving',
                'description'      => 'Club selam terbesar di kawasan Kuta-Seminyak, spesialis rescue diving dan aktif mendukung operasi SAR laut di perairan selatan Bali.',
                'contact_phone'    => '+62 361 888 0008',
                'contact_email'    => 'kutasea@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Sanur Dive Society',
                'city'             => 'Denpasar',
                'area'             => 'denpasar',
                'icon'             => '🐠',
                'established_year' => 2005,
                'member_count'     => 72,
                'specialty'        => 'Scuba & Night Diving',
                'description'      => 'Club selam berbasis di Sanur dengan spesialisasi scuba diving dan night diving, sering menjadi tuan rumah event internasional di Bali.',
                'contact_phone'    => '+62 361 999 0009',
                'contact_email'    => 'sanur@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Amed Underwater Explorer',
                'city'             => 'Karangasem',
                'area'             => 'karangasem',
                'icon'             => '🔭',
                'established_year' => 2017,
                'member_count'     => 35,
                'specialty'        => 'Marine Survey & Research',
                'description'      => 'Club selam muda yang fokus pada survei dan penelitian bawah laut di perairan Amed, berkolaborasi dengan institusi penelitian kelautan nasional.',
                'contact_phone'    => '+62 363 100 0010',
                'contact_email'    => 'amed@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Canggu Reef Riders',
                'city'             => 'Badung',
                'area'             => 'badung',
                'icon'             => '🏊',
                'established_year' => 2019,
                'member_count'     => 28,
                'specialty'        => 'Reef Diving & Community',
                'description'      => 'Club selam komunitas di kawasan Canggu, memadukan passion selam dengan gaya hidup aktif dan program pelestarian reef di perairan barat Bali.',
                'contact_phone'    => '+62 361 200 0011',
                'contact_email'    => 'canggu@possibali.org',
                'is_verified'      => false,
                'is_champion'      => false,
                'is_active'        => true,
            ],
            [
                'name'             => 'Tabanan Coral Club',
                'city'             => 'Tabanan',
                'area'             => 'tabanan',
                'icon'             => '🪨',
                'established_year' => 2016,
                'member_count'     => 33,
                'specialty'        => 'Freediving & Apnea',
                'description'      => 'Club selam di Tabanan yang mengembangkan olahraga freediving dan apnea, aktif mencetak atlet freediving muda berbakat dari wilayah barat Bali.',
                'contact_phone'    => '+62 361 300 0012',
                'contact_email'    => 'tabanan@possibali.org',
                'is_verified'      => true,
                'is_champion'      => false,
                'is_active'        => true,
            ],
        ];

        foreach ($clubs as $club) {
            Club::create([
                'name'             => $club['name'],
                'slug'             => Str::slug($club['name']) . '-' . Str::random(4),
                'city'             => $club['city'],
                'area'             => $club['area'],
                'icon'             => $club['icon'],
                'established_year' => $club['established_year'],
                'member_count'     => $club['member_count'],
                'specialty'        => $club['specialty'],
                'description'      => $club['description'],
                'contact_phone'    => $club['contact_phone'],
                'contact_email'    => $club['contact_email'],
                'is_verified'      => $club['is_verified'],
                'is_champion'      => $club['is_champion'],
                'is_active'        => $club['is_active'],
            ]);
        }
    }
}